[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Isaac Lab Environments"
description="Learn to Use IsaacLab and add some common utils for convenient using."
repository = "https://github.com/FerryRain/IsaacLabLearn"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}

[python.pipapi]
requirements = [
    "h5py",
    "tensorboard",
    "rl-games==1.6.1",
]

modules = [
    "h5py",
    "tensorboard",
    "stable_baselines3",
    "rl_games",
]

use_online_index=true

[[python.module]]
name = "RL_Policy"
